name: LobbyItems
version: LI-2.0
api: 3.0.0-ALPHA11
main: VL\LobbyItems
author: VL (Real Author) | Zadezter
commands:
    build:
        description: Lobby with a Build-mode command!
    lobby:
        description: Lobby command!
    fly:
        description: Fly access command!
